### ISSUE TITLE
Post not showing

### ISSUE THREAD

**Issue by davinic** [dadsquatch/f5oclock#20]
The article with the title *Mueller gathers evidence that 2017 Seychelles meeting was effort to establish back channel to Kremlin* was not showing in the list, despite hundreds of comments and upvotes:

<img width="985" alt="screen shot 2018-03-07 at 7 11 35 pm" src="https://user-images.githubusercontent.com/369744/37127465-82a491d2-223b-11e8-83fb-b56cac79d9cd.png">

I captured the [json result](https://github.com/dadsquatch/f5oclock/files/1791516/rising.json.txt) within a couple seconds of the screenshot. The json includes the article. 

A few minutes later, with [this json result](https://github.com/dadsquatch/f5oclock/files/1791523/rising-after.json.txt), the article appeared:

<img width="995" alt="screen shot 2018-03-07 at 7 17 51 pm" src="https://user-images.githubusercontent.com/369744/37127639-4b39ee12-223c-11e8-8ec6-cf56b4b9b1cb.png">

**Comment by dantheuber** [comment]
reddit's api does some weird things, new app version is rolled out which should account for things like this. Please Reopen this issue if you notice something going missing again.
