### ISSUE TITLE
Hovering over the article title no longer shows the whole title (Desktop)

### ISSUE THREAD

**Issue by katcaola** [dadsquatch/f5oclock#28]
The old version of F5Oclock had the helpful feature of showing the full article title when hovering the mouse over the title. I liked that it saved me from having to click on every link I couldn't read.

I know this is desktop specific and a major code overhaul is happening, but ff possible, please re-implement this feature.

**NOTES:**
-  Using Firefox Quantum for Ubuntu 16.04 (v59.0.2 64-bit)
-  appears in both card and table view
-  I view the website exclusively in Dark mode

**Comment by dadsquatch** [comment]
Just did a PR/Merge for this and it should be fixed.

**Comment by katcaola** [comment]
Yay, I can view titles again. Thanks for the fix!
