### ISSUE TITLE
Page is using development build of react

### ISSUE THREAD

**Issue by DBosley** [dadsquatch/f5oclock#30]
My React dev tools indicate that the production site is using the development build of React. The production build should be used for final deploys.

**Comment by DBosley** [comment]
I just looked through the src code and it looks like you're using angular. Is this not the site that's deployed to f5oclock.com?

**Comment by dantheuber** [comment]
Thanks, i've updated this repo to reflect the current state of the site. This repo will be used for reporting issues and feedback. Source code for current site is no longer public.

I've added a task to get the react building properly.
