### ISSUE TITLE
Don't truncate titles?

### ISSUE THREAD

**Issue by tommcc** [dadsquatch/f5oclock#4]
Many headlines on /r/politics nowadays are a little wordy, and the truncated preview can leave out really important info that requires you to then hover or click to even understand the headline.

I don't see any major downside to just showing the whole title in the table. Thoughts?

**Comment by dadsquatch** [comment]
I had it doing this originally, but on mobile it causes them to drop down into many different lines and then makes the icons to the right ugly.

**Comment by mikeatlas** [comment]
You can do different CSS layouts for different viewports (mobile and desktop dimensions)
