### ISSUE TITLE
Visiting site causes redirect to missing resource/url

### ISSUE THREAD

**Issue by kheck** [dadsquatch/f5oclock#7]
repro steps:
Don't visit f5oclock.com for a few hours (hard to do)
go to f5oclock.com

Expected results:
A torrent of glorious political news coverage

Actual results:
Browser redirect to something like "http://www.f5oclock.com/TiUXc/"
Page content of "Cannot GET /TiUXc/"

Workaround:
Try to load "f5ocklock.com" again.  It'll work the second time

**Comment by dantheuber** [comment]
Thanks @kheck for letting us know about this.. I've added some additional logging analytics that I'm hoping will help pinpoint where this issue is coming from. If you happen across any additional information that you find to be relevant, please update this issue thread.

**Comment by dantheuber** [comment]
going to close this issue. Please reopen with additional information requested above if you experience this in the future.
