### ISSUE TITLE
forking/running for my own purposes

### ISSUE THREAD

**Issue by mikeatlas** [dadsquatch/f5oclock#9]
I hit your site daily, and would like to customize it to my liking - could you post some instructions on how to deploy our own instance? Requirements? And what license is this? MIT?

* Particularly, there are a handful of domains which get traction in r/politics but usually are not actually breaking news, but are left-of-center opinion and analysis (shareblue, vox, slate, huffpo in particular). Even with a lot of upvotes, they're not breaking news stories. 
* Sometimes stories get some traction after the 30min cutoff - I'd like to see it at 1hr instead and raise the traction thresholds a bit higher. 
* I'd like to weight some sources higher than others with preference for news-breaking and investigative journalism sources (reuters, ap, nytimes, wsj, wapo, etc) and others, like the "coverage reporting" with medium signals (eg abc, cnn, nbc).

Personally these tweaks I think would make for a higher value "quick read" of the headlines over r/politics, and would keep the focus on the biggest 💥 s :)

**Comment by dadsquatch** [comment]
We are working on mostly backend stuff right now which is collection of data (posts and stories). Right now it just uses the Reddit API, which very well may change to something a bit more in depth. 

Down the pipeline hopefully Q1 we will hopefully be implementing much of what you are referring to here as far as front end filters with angular to request from the cache more specific details. We just rolled out an that removed the use of databases completely. The hard part to this whole project is I don't want users to have to log in to get what they are looking for and that means losing their preferences or using a long set cookie of some sort. We are still brainstorming.

**Comment by dantheuber** [comment]
I've updated the `README.md` to include instructions for local development and updated the licensing information.
